baseURL = 'https://drhanson.net/'
languageCode = 'en-us'
title = 'David R. Hanson'
uglyURLs = true
disableKinds = [ "rss", "sitemap", "taxonomy", "term" ]
cleanDestinationDir = true
enableGitInfo = true
[frontmatter]
  lastmod = [ ':fileModTime', ':git', ':default' ]
[page]
  NextPrevInSectionSortOrder = 'asc'
[module]
  [[module.imports]]
    path = "github.com/drh/hugo-utilities"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
theme = [ "hugo-utilities" ]
[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
