baseURL = 'https://drhanson.net/'
languageCode = 'en-us'
title = 'David R. Hanson'
uglyURLs = true
cleanDestinationDir = true
enableGitInfo = true
[frontmatter]
  lastmod = [ ':fileModTime', ':git', ':default' ]
